FROM golang:1.18.3-alpine3.16 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download -x

COPY . .

RUN go build -o main .

FROM alpine:3.16 AS runner

WORKDIR /app

COPY --from=builder /app/main ./

CMD [ "./main" ]
