version: "3.8"

services:
  myservice:
    image: myservice:1.1
    container_name: myservice
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 32m
    ports:
      - 8081:8080
